-- AOS SECURITY ROLLBACK ANCHOR
-- Preserved before anon/PUBLIC exposure hardening.
-- Execute only if rollback is deliberately required.

GRANT EXECUTE ON FUNCTION public.assign_internal_work_order_number_v1() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.assign_inventory_barcode() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.authorize_labor_insert() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.authorize_ndt_session() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.billing_insert_v1(p_tenant_id uuid, p_report_id uuid, p_job_id uuid, p_amount numeric, p_created_by uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.block_legacy_cert_modifications() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.calculate_stabilizer_estimate_v1(p_nominal_body_od numeric, p_blade_count integer, p_starting_blade_od numeric, p_desired_blade_od numeric, p_crown_length numeric, p_blade_width numeric, p_blade_length numeric, p_material_type text, p_strip_required boolean) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.certification_signoff_v1(p_signoff_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.check_weld_continuity(p_employee_id uuid, p_weld_process text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.compliance_override_v1(p_finding_id uuid, p_reason text, p_triggered_by uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.compute_estimator_confidence_v1() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.compute_job_variance_v1(p_job_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_and_link_third_party_report_v1(p_job_id uuid, p_report_file_url text, p_declared_result text, p_inspection_date date, p_mark_verified boolean) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_and_link_third_party_visit_v1(p_job_id uuid, p_visit_date date, p_mark_completed boolean) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_customer_v1(p_name text, p_email text, p_phone text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_job_actual_summary_snapshot_v1() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_job_quote_snapshot_v1(p_job_id uuid, p_estimator_version text, p_quoted_total_price numeric, p_quoted_labor_hours numeric, p_quoted_material_cost numeric) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_tool_v1(p_customer_id uuid, p_serial_number text, p_tool_type text, p_blade_count integer, p_nominal_body_od numeric, p_notes text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.current_user_has_permission_v1(p_permission_key text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.employee_has_permission_v1(p_tenant_id uuid, p_profile_id uuid, p_permission_key text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.enforce_job_stage_transition() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.enforce_labor_scope_qualification() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.enforce_mutation_registry() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.estimator_activation_eligibility_v1() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.generate_inventory_barcode(p_item_category text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.generate_job_narrative(p_job_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.generate_job_narrative_v1(p_job_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.generate_job_quote_v1(p_job_id uuid, p_nominal_body_od numeric, p_blade_count integer, p_starting_blade_od numeric, p_desired_blade_od numeric, p_crown_length numeric, p_blade_width numeric, p_blade_length numeric, p_material_type text, p_strip_required boolean) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_admin_compliance_flags_v1() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_available_emailed_reports_v1() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_current_customer_id() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_current_tenant_id() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_current_user_identity_v1() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_current_user_permissions_v1() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_customer_jobs_v1(p_customer_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_customers_dashboard_v1() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_entity_compliance_status(p_entity_type compliance_entity_type, p_entity_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_job_compliance_status(p_job_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_jobs_dashboard_v1() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_my_dashboard_layout_v1() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_next_export_version(p_lifecycle_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_third_party_report_dashboard_v1() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_tools_dashboard_v1() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.global_system_search_v1(p_query text, p_limit integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.handle_certification_signoff_trigger() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.handle_failed_inspection() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.increment_estimator_job_count_v1() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.initiate_certification_process(p_profile_id uuid, p_category certification_type, p_scope certification_scope, p_admin_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.invalidate_exports_on_lifecycle_change() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.issue_certification_export(p_lifecycle_id uuid, p_pdf_storage_path text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.job_stage_transition_core_v1(p_job_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.job_stage_transition_v1(p_job_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.job_stage_transition_v1_internal(p_job_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.lifecycle_transition_v1(p_lifecycle_id uuid, p_new_state certification_lifecycle_state, p_reason text, p_triggered_by uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.link_existing_third_party_report_to_job_v1(p_report_id uuid, p_job_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.mark_third_party_report_assignment_complete_v1(p_report_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.process_expired_certifications() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.process_inspection_email(p_email_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.process_inspection_email_unassigned_v1(p_email_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.process_inventory_from_snapshot() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.process_lot_usage() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.record_job_qc_decision_v1(p_job_id uuid, p_decision_source text, p_outcome text, p_reroute_stage job_stage, p_reason text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.refresh_job_compliance_after_report_v1() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.regenerate_job_narrative(p_job_id uuid, p_reason text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.resolve_admin_compliance_flag_v1(p_finding_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.route_job_stage_with_reason_v1(p_job_id uuid, p_target_stage text, p_reason text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.run_full_compliance_scan() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.scan_employee_certifications() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.scan_equipment_calibrations() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.scan_job_compliance() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.select_post_inspection_stage_v1(p_job_id uuid, p_next_stage text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.set_job_priority_flags_v1(p_job_id uuid, p_severe_damage boolean, p_rush_job boolean) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.set_my_dashboard_grid_layout_v1(p_widget_key text, p_is_visible boolean, p_x_position integer, p_y_position integer, p_width_units integer, p_height_units integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.set_my_dashboard_widget_layout_v1(p_widget_key text, p_is_visible boolean, p_sort_order integer, p_widget_size text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.set_my_dashboard_widget_visibility_v1(p_widget_key text, p_is_visible boolean) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.trg_refresh_job_compliance_after_report_v1() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.update_estimator_rates_v1(p_new_labor_rate numeric, p_new_steel_cost numeric, p_new_stainless_cost numeric, p_new_hm_cost numeric, p_new_deposition_rate numeric, p_new_bevel_multiplier numeric, p_new_service_fee numeric, p_new_strip_factor numeric) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.update_narrative_addendum(p_job_id uuid, p_addendum text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.validate_certification_export(p_lifecycle_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.verify_third_party_report_v1(p_report_id uuid, p_verified_by uuid) TO PUBLIC;
GRANT USAGE ON SCHEMA public TO PUBLIC;
