'use client'

import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'

type AdminFlagRow = {
  finding_id: string
  tenant_id: string
  entity_type: string
  entity_id: string
  rule_code: string
  severity: string
  description: string | null
  detected_at: string | null
  resolved: boolean | null
  resolved_at: string | null
}

export default function AdminFlagsPage() {
  const [flags, setFlags] = useState<AdminFlagRow[]>([])
  const [loading, setLoading] = useState(true)
  const [workingId, setWorkingId] = useState<string | null>(null)
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')

  const loadFlags = async () => {
    setLoading(true)
    setError('')
    setMessage('')

    const { data, error } = await supabase.rpc('get_admin_compliance_flags_v1')

    if (error) {
      setError(error.message)
      setFlags([])
    } else {
      setFlags((data ?? []) as AdminFlagRow[])
    }

    setLoading(false)
  }

  useEffect(() => {
    void loadFlags()
  }, [])

  const resolveFlag = async (findingId: string) => {
    setWorkingId(findingId)
    setError('')
    setMessage('')

    const { error } = await supabase.rpc('resolve_admin_compliance_flag_v1', {
      p_finding_id: findingId,
    })

    if (error) {
      setError(error.message)
    } else {
      setMessage('Admin flag resolved.')
      await loadFlags()
    }

    setWorkingId(null)
  }

  if (loading) {
    return <main className="p-6">Loading admin flags...</main>
  }

  return (
    <main className="p-6 space-y-6">
      <div>
        <h1 className="text-2xl font-semibold">Admin Compliance Flags</h1>
        <p className="text-sm text-gray-400">
          Review unresolved non-blocking compliance flags generated by controlled workflow actions.
        </p>
      </div>

      {message ? (
        <div className="rounded border border-green-700 bg-green-950 p-3 text-green-300">
          {message}
        </div>
      ) : null}

      {error ? (
        <div className="rounded border border-red-700 bg-red-950 p-3 text-red-300 break-words">
          {error}
        </div>
      ) : null}

      {flags.length === 0 ? (
        <div className="rounded border border-gray-800 bg-gray-900 p-4">
          No unresolved admin flags found.
        </div>
      ) : (
        <div className="space-y-4">
          {flags.map((flag) => (
            <div
              key={flag.finding_id}
              className="rounded border border-yellow-800 bg-yellow-950/30 p-4 space-y-3"
            >
              <div className="space-y-1">
                <p className="font-semibold">
                  {flag.severity} — {flag.rule_code}
                </p>

                <p className="text-sm text-gray-300 break-words">
                  {flag.description ?? 'No description provided.'}
                </p>

                <p className="text-sm text-gray-400 break-all">
                  Finding ID: {flag.finding_id}
                </p>

                <p className="text-sm text-gray-400 break-all">
                  Entity: {flag.entity_type} / {flag.entity_id}
                </p>

                <p className="text-sm text-gray-400">
                  Detected: {flag.detected_at ?? 'Unknown'}
                </p>

                <p className="text-sm text-gray-400">
                  Resolved: {String(flag.resolved)}
                </p>
              </div>

              <button
                onClick={() => resolveFlag(flag.finding_id)}
                disabled={workingId === flag.finding_id}
                className="px-4 py-2 bg-yellow-700 text-white rounded disabled:opacity-50"
              >
                {workingId === flag.finding_id ? 'Resolving...' : 'Resolve Flag'}
              </button>
            </div>
          ))}
        </div>
      )}
    </main>
  )
}